-function(window, module) {
'use strict';var m="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;function n(){m.Symbol||(m.Symbol=q);n=function(){}}var r=0;function q(a){return"jscomp_symbol_"+a+r++}function t(){n();m.Symbol.iterator||(m.Symbol.iterator=m.Symbol("iterator"));t=function(){}}function u(a){t();if(a[m.Symbol.iterator])return a[m.Symbol.iterator]();var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}}
function v(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};function w(a,b){if(!a)throw Error((void 0===b?null:b)||"Assertion failed");}function x(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];console.log.apply(console,[].concat(b instanceof Array?b:v(u(b))))};function y(){this.b=[];this.a=[]}y.prototype.add=function(a){var b={};this.a.push(b);this.b.push(a);return function(){var a=this.a.indexOf(b);this.b.splice(a,1);this.a.splice(a,1)}.bind(this)};y.prototype.call=function(){for(var a=u(this.b),b=a.next();!b.done;b=a.next())b=b.value,b()};function z(a){a=a.getBoundingClientRect();return!(0>a.bottom||0>a.right||a.top>window.innerHeight||a.left>window.innerWidth)};function A(a,b,c){this.width=a;this.height=b;this.a=new Set(c);this.changeCallbacks=new y}Object.defineProperties(A.prototype,{agents:{configurable:!0,enumerable:!0,get:function(){return this.a}}});function B(){this.y=this.x=50;this.a=this.z=0;this.changeCallbacks=new y}B.prototype.right=function(a){w(Number.isFinite(a));this.a+=a};B.prototype.left=function(a){w(Number.isFinite(a));this.a-=a};function C(a,b){w(Number.isFinite(b));a.goTo(a.x+b*a.h,a.y+b*a.i,a.z)}
B.prototype.goTo=function(a,b,c){w(Number.isFinite(a));w(Number.isFinite(b));w(Number.isFinite(c));c=a-this.x;for(var k=b-this.y,l=Math.ceil(Math.sqrt(c*c+k*k)/4),f=0;f<l;f++)this.x+=c/l,this.y+=k/l,this.changeCallbacks.call();this.x=a;this.y=b;this.changeCallbacks.call();return Promise.resolve()};Object.defineProperties(B.prototype,{h:{configurable:!0,enumerable:!0,get:function(){return-Math.sin(2*this.a*Math.PI)}},i:{configurable:!0,enumerable:!0,get:function(){return Math.cos(2*this.a*Math.PI)}}});function D(a,b){return new E(a,b)}function E(a,b){w(Number.isFinite(a),"x = "+a+" must be a finite number");w(Number.isFinite(b),"y = "+b+" must be a finite number");this.x=a;this.y=b}function F(a){return Math.sqrt(a.x*a.x+a.y*a.y)}function G(a,b){w(Number.isFinite(b),"magnitude = "+b+" must be a finite number");var c=F(a);return 0!==c?a.scale(b/c):D(0,0)}
E.prototype.scale=function(a){w(Number.isFinite(a),"magnitude = "+a+" must be a finite number");return 0==a||0==this.x&&0==this.y?D(0,0):D(a*this.x,a*this.y)};E.prototype.add=function(a){return D(this.x+a.x,this.y+a.y)};E.prototype.toString=function(){return"V("+this.x+", "+this.y+")"};
function H(a,b){var c=this;this.width=a;this.height=b;this.changeCallbacks=new y;this.a=new Set;var k=+new Date;setInterval(function(){var a=+new Date,b=(a-k)/1E3;k=a;if(!(0>=b)){for(var a=new Map,h=u(c.a),d=h.next();!d.done;d=h.next())a.set(d.value,D(0,0));h=u(c.a);for(d=h.next();!d.done;d=h.next())for(var p=d.value,d=u(c.a),e=d.next();!e.done;e=d.next())if(e=e.value,p!==e){var e=e.b,g=p.b,e=D(e.x-g.x,e.y-g.y),g=F(e);40>g&&(g=40);e=G(e,1).scale(66740.8*1E15/Math.pow(g,2));a.set(p,a.get(p).add(e))}h=
[];p=u(c.a);for(d=p.next();!d.done;d=p.next())d=d.value,e=a.get(d),g=e.scale(b/1E15),console.log("dV from forces "+g),d.a=d.a.add(g),g=F(d.a),g=Math.max(0,g-b*g*.05),10<=g||10<F(e)/1E15?(console.log(String(g)),d.a=G(d.a,g)):d.a=D(0,0),0<F(d.a)&&(e=d.a.scale(b),d.b=d.b.add(e),h.push(d));for(b=0;b<h.length-1;b++)a=h[b],p=b+Math.floor(Math.random()*h.length-b),h[b]=h[p],h[p]=a;b=u(h);for(d=b.next();!d.done;d=b.next())d.value.changeCallbacks.call()}},20)}
Object.defineProperties(H.prototype,{agents:{configurable:!0,enumerable:!0,get:function(){return new Set(this.a)}}});function I(a,b,c){this.b=D(void 0===b?0:b,void 0===c?0:c);this.a=D(0,0);this.c=null;this.changeCallbacks=new y}I.prototype.goTo=function(a,b,c){var k=this;if(this.c){var l=function(){return k.goTo(a,b,c)};return this.c.then(l,l)}return this.c=new Promise(function(b){return b()})};
Object.defineProperties(I.prototype,{x:{configurable:!0,enumerable:!0,get:function(){return this.b.x}},y:{configurable:!0,enumerable:!0,get:function(){return this.b.y}},z:{configurable:!0,enumerable:!0,get:function(){return 0}}});function J(a,b){var c=a+" !== "+b;if(a!==b)throw Error((void 0===c?null:c)||"Assertion failed");};function K(a,b){var c=this;this.b=0;this.f=1E3*Math.random();this.c=a;this.a=b;this.cancel=b.changeCallbacks.add(function(){var a=b.x,l=b.y,f=b.z;z(c.c.b)&&(a-=0,l-=0,f-=0,c.b+=Math.sqrt(a*a+l*l+f*f),f=c.c.c,f.fillStyle="rgba(0, 0, 0, 0.75)",f.beginPath(),f.arc(c.a.x,c.a.y,8,0,2*Math.PI),f.fill(),f.fillStyle="hsla("+(c.f+.05*c.b)+", 50%, 50%, 1.0)",f.strokeStyle="rgba(255, 255, 255, 1.0)",f.beginPath(),f.arc(c.a.x,c.a.y,6,0,2*Math.PI),f.fill(),f.stroke())})}
function L(a){var b=this;this.a=a;this.b=document.createElement("canvas");this.b.width=this.a.width;this.b.height=this.a.height;this.c=this.b.getContext("2d");this.c.fillStyle="black";this.c.fillRect(0,0,this.a.width,this.a.height);this.f=new Map;this.g();this.a.changeCallbacks.add(this.g.bind(this));var c=+new Date;setInterval(function(){var a=+new Date,l=(a-c)/1E3;c=a;z(b.b)?b.c.fillStyle="rgba(0, 0, 0, "+.5*l+")":b.c.fillStyle="black";b.c.fillRect(0,0,b.a.width,b.a.height)},100)}
L.prototype.g=function(){for(var a=u(this.f),b=a.next();!b.done;b=a.next())b.value.cancel();this.f=new Map;a=u(this.a.agents);for(b=a.next();!b.done;b=a.next())b=b.value,this.f.set(b,new K(this,b))};function M(){}M.prototype.test=function(){x("Let's testTheTurtles()!");N()};M.prototype.addFlatCanvasWithTurtles=function(a){var b=new A(512,512,[]),c=new L(b);a.appendChild(c.b);N(b);return b};
M.prototype.addFlatCanvasWithFlatland=function(a){function b(){return.5+(Math.random()+Math.random()+Math.random())/3}var c=new H(512,512),k=new L(c);a.appendChild(k.b);a=new I(0,50,50);a.a=D(150*b(),-50*b());c.a.add(a);a=new I(0,400,200);a.a=D(8*b(),200*b());c.a.add(a);a=new I(0,150,175);a.a=D(-4*b(),100*b());c.a.add(a);for(a=0;40>a;a++)k=new I(0,200+50*b(),200+50*b()),c.a.add(k);c.changeCallbacks.call();return c};
function N(a){a=void 0===a?new A(512,512,[]):a;var b=new B;a.a.add(b);a.changeCallbacks.call();J(50,b.x);J(50,b.y);C(b,50);J(50,b.x);J(100,b.y);b.right(.25);C(b,25);J(25,b.x);J(100,b.y);b.left(.375);C(b,100);for(a=0;12>a;a++)b.left(.0625),C(b,10);C(b,100);b.left(.25);C(b,200);for(a=0;6>a;a++)b.left(.0625),C(b,10);C(b,50);console.log("Test complete.")}var O=new M;"object"===typeof module&&null!=module&&(module.exports=O);"object"===typeof window&&null!=window&&(window.vxq=O);
}.call(typeof window == 'object' ? window: typeof this == 'object' ? this: null,typeof window == 'object' ? window : null,typeof module == 'object' ? module : null)
