#!/bin/bash
set -eux;

base="$(dirname "$0")";

closure_jar="${base}/../node_modules/google-closure-compiler/compiler.jar";
output_wrapper="-function(window,module){
%output%
}.call(typeof
window=='object'?window:typeof
this=='object'?this:null,typeof
window=='object'?window:null,typeof
module=='object'?module:null)";

java -jar "${closure_jar}" \
  --js "vxq/**.js" \
  --js "!vxq/**.externs.js" \
  \
  --externs=vxq/public.externs.js \
  --externs=vxq/environment.externs.js \
  \
  --entry_point=vxq.main \
  --output_wrapper="${output_wrapper}" \
  \
  --js_output_file=tmp/prod/vxq.js \
  \
  --language_in=ECMASCRIPT6_STRICT \
  --language_out=ECMASCRIPT5_STRICT \
  --compilation_level=ADVANCED_OPTIMIZATIONS \
  \
  --use_types_for_optimization=true \
  --warning_level=VERBOSE \
  --jscomp_error=lintChecks \
  --jscomp_error=fileoverviewTags \
  --jscomp_error=nonStandardJsDocs \
  --jscomp_error=suspiciousCode \
  --jscomp_error=deprecated \
  --jscomp_error=accessControls \
  --jscomp_error=undefinedVars \
  --jscomp_error=undefinedNames \
  --jscomp_error=visibility \
  --jscomp_error=externsValidation \
  --jscomp_error=checkTypes \
  --jscomp_error=missingReturn \
  --jscomp_error=checkVars \
  --jscomp_error=missingProvide \
  --jscomp_error=missingRequire \
  --jscomp_error=missingProperties \
;