#!/bin/bash
set -veuxo pipefail;

version="$(node -e "console.log(require('./package.json').version);")";
branch="$(git rev-parse --abbrev-ref HEAD)";
remote="$(git config branch.${branch}.remote)";

git add -A;
git commit --no-verify -m "${version}";
git tag "${version}";
git push "${remote}" --tags;
git push "${remote}" "${branch}";
git push "${remote}" "${branch}:gh-pages" || \
    echo "Optimistically assuming that gh-pages update failed correctly " \
         "because this release is an update to a previous version, not the " \
         "latest version.";
