#!/bin/bash
set -veuxo pipefail;

ancestor_count="$(git rev-list --count HEAD)";
# Update package.json to specify a -dev prelease version using this git
# ancestor count, and automatically resolve version number conflicts based
# on the greater version number.
node <<END
  const fs = require('fs');
  const semver = require('semver');

  const rawData = fs.readFileSync('package.json', {encoding: 'utf8'});

  const rawDataWithVersionConflictResovled = rawData.replace(
      /\n<<<<<<<[^\n]*\n\s*"version"\s*:\s*([^,]+),\n=======\n\s*"version"\s*:\s*([^,]+),\n>>>>>>>[^\n]+\n/,
      (match, firstVersion, secondVersion) =>
        '"version": ' + (semver.gte(JSON.parse(firstVersion), JSON.parse(secondVersion)) ? firstVersion : secondVersion) + ',');

  const data = JSON.parse(rawDataWithVersionConflictResovled);
  data.version =
    semver.inc(data.version, 'prerelease', 'dev')
        .replace(/\d+\$/, ${ancestor_count});
  fs.writeFileSync('package.json', JSON.stringify(data, null, 2) + '\n');
END

git add package.json;
npm run prepublish && ( \
  echo "exit status 0" | tee zdist/00-SUCCESS \
) || ( \
  echo "exit status $?" | tee zdist/00-FAILURE \
);
git add zdist/;
